# keyboard inputs
input {
	# i like speed.
	repeat_delay = 250
	repeat_rate = 50

	kb_layout = us
	# since i use caps lock to capitalize my letters, i use this.
  # this can be commented out if not needed
	#kb_options = caps:ctrl_modifier
}

general{
  resize_on_border = true
}

# wayland stuff...
xwayland {
  force_zero_scaling = false
}

# monitors
monitor = , highrr, auto, 1 # every other monitor (including desktop or random)
monitor = eDP-1, highrr, auto, 2 # embedded laptop monitor
