# application specific
windowrule = float true, size 900 550, center true, match:class org.gnome.Nautilus # file manager
windowrule = float true, maximize true, match:class org.gnome.Totem # video application
windowrule = float true, match:class yad # yet another dialog

# application window rules
windowrule = workspace special:disc silent, match:class discord
workspace = special:disc, gapsout:30
windowrule = workspace special:notes silent, match:class obsidian
workspace = special:notes, gapsout:30

# file dialogs
windowrulev2 = size 890 550, title:^(File Upload)$ # firefox

# layer rules
#layerrule = blur, logout_dialog # wlogout blur
